### ISSUE TITLE
Bug: Navbar UI Overlap

### ISSUE THREAD

**Issue by bliutech** [uclaacm/acmcyber.com#111]
There is a bit of a strange issue with the navigation bar having some overlap with the scrollbar. Two images below shows what it normally looks like on other sites and what it looks like on our sites. Found on Chrome.

<img width="267" alt="image" src="https://github.com/uclaacm/acmcyber.com/assets/67720812/94628695-f0ae-4540-b484-5d72933a371a">

<img width="267" alt="image" src="https://github.com/uclaacm/acmcyber.com/assets/67720812/b866654a-5c28-4dce-b9b1-584529a877e2">

**Comment by Arc-blroth** [comment]
This seems to be because the header has a positive z-index and the scrollbar gets rendered at z-index 0 everywhere. Fix will be to reduce header z-index to 0 and make everything else negative.

**Comment by Arc-blroth** [comment]
Alternatively unsetting overflow-x: hidden on the body also fixes it https://stackoverflow.com/a/13028609 and is probably a better solution
