### ISSUE TITLE
feat: Sanitize Markdown Inputs

### ISSUE THREAD

**Issue by bliutech** [uclaacm/acmcyber.com#125]
Currently, to display the generated Markdown, we are using `dangerouslySetInnerHTML` which has some complex implications for security. To be truly cautious, it would be nice to use `DOMPurify` to sanitize all contributed blog posts. `isomorphic-dompurify` is probably the best library to use due to server side rendering. https://github.com/kkomelin/isomorphic-dompurify There may need to be a bit of wrangling with the `Next.js` build configuration due to including this library. https://github.com/kkomelin/isomorphic-dompurify/issues/54

**Comment by r2dev2** [comment]
We manually approve all markdown before merging. If one of our contributors wanted to be malicious (with 0 important cookies), they could just add a full html page.
