### ISSUE TITLE
🐞Bug: Miscellaneous Mobile UI Bugs

### ISSUE THREAD

**Issue by bliutech** [uclaacm/acmcyber.com#81]
Tested on iPhone Safari.

~~Missing popup backdrop for some reason?~~
![image](https://github.com/uclaacm/cyber.uclaacm.com/assets/67720812/f613e28e-f418-400d-a712-c82fd762fc15)

~~Background does not completely cover page.~~
![image](https://github.com/uclaacm/cyber.uclaacm.com/assets/67720812/20fe67e5-40d2-4618-96be-5bad65641ebf)

Does not account for mobile view but should be a quick fix but doing flex column rather than flex row potentially with media queries.
![image](https://github.com/uclaacm/cyber.uclaacm.com/assets/67720812/3c60421f-2710-47eb-9d56-a70bc91c6c35)

**Comment by Arc-blroth** [comment]
"Background does not completely cover page." was fixed by #168

**Comment by bliutech** [comment]
Most of these were resolved. Closing for organization purposes. Will reopen a separate issue.
